asteroid/urls.py
from django.conf.urls import patterns, url

from asteroid import views

urlpatterns = patterns('',
    url(r'^$', views.screen1, name='screen1'),
    url(r'^welcome/$', views.welcome, name='welcome'),
    url(r'^about/$', views.about, name='about'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^browse/$', views.browse, name='browse'),
    url(r'^browse-genre/(?P<g>\w+)/$', views.browse_genre, name='browse_genre'),
    url(r'^search/$', views.search, name='search'),
    url(r'^index/$', views.index, name='index'),
    url(r'^indextop/$', views.indextop, name='indextop'),
    url(r'^(?P<movie_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<movie_id>\d+)/voting/$', views.voting, name='voting'),
)

moviewhereabouts/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'moviewhereabouts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^asteroid/', include('asteroid.urls', namespace="asteroid")),
    url(r'^admin/', include(admin.site.urls)),
)

asteroid/models.py
from django.db import models

class User(models.Model):
    username = models.CharField(max_length = 40)
    user_fav = models.CommaSeparatedIntegerField(max_length = 50)

    def __str__(self):
        return self.username

class Movie(models.Model):
    id = models.IntegerField(default = 0, primary_key=True)
    imdb_id = models.CharField(max_length = 25, default = '')
    tmdb_id = models.CharField(max_length = 25, default = '')
    title = models.CharField(max_length = 100)
    movie_synopsis = models.CharField(max_length = 1800)
    critics_score = models.IntegerField(default = 0)
    votes = models.IntegerField(default = 10)
    img = models.CharField(max_length = 50, default = 'Image unavailable')
    s_img = models.CharField(max_length = 70, default = '')
    l_img = models.CharField(max_length = 70, default = '')
    category = models.CharField(max_length = 20)
    genre = models.CharField(max_length = 60)

    def __str__(self):
        return self.title

class Cast(models.Model):
    movie = models.ForeignKey(Movie, unique=True)
    actor = models.CharField(max_length = 200)
    character = models.CharField(max_length = 200)

    def __str__(self):
        return self.movie.title

class Feedback(models.Model):
    fname = models.CharField(max_length = 25, default='unknown')
    fmail = models.EmailField(max_length = 50, default='unknown@unknown.com')
    msg = models.CharField(max_length = 200, default='no msg')

    def __str__(self):
        return self.fname

asteroid/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from asteroid.models import Movie, Cast, Feedback
import urllib
from urllib2 import urlopen
import requests
import json
from rottentomatoes import RT
from django.db import connection
from urllib import urlencode
import zlib
from django.core.validators import validate_email
from django.core.exceptions import ValidationError

def browse(request):
    movies = Movie.objects.all()
    paginator = Paginator(movies, 9)
    page = request.GET.get('page')

    try:
        movies = paginator.page(page)
    except PageNotAnInteger:
        movies = paginator.page(1)
    except EmptyPage:
        movies = paginator.page(paginator.num_pages)

    return render(request, 'asteroid/browse.html', {'movies': movies})

def browse_genre(request, g):
    if g:
        for movie in Movie.objects.all():
            found_movies = Movie.objects.filter(genre__icontains=g)
    else:
        found_movies = Movie.objects.all()
    paginator = Paginator(found_movies, 9)
    page = request.GET.get('page')

    try:
        found_movies = paginator.page(page)
    except PageNotAnInteger:
        found_movies = paginator.page(1)
    except EmptyPage:
        found_movies = paginator.page(paginator.num_pages)

    return render(request, 'asteroid/browse-genre.html', {'movies': found_movies})

def index(request):
    latest_movies = Movie.objects.all()
    context = {'latest_movies': latest_movies}
    return render(request, 'asteroid/index.html', context)

def indextop(request):
    top_movies = Movie.objects.order_by('-votes')
    context = {'top_movies': top_movies}
    return render(request, 'asteroid/indextop.html', context)

def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request, 'asteroid/detail.html', {'movie': movie})

def voting(request, movie_id):
    try:
        m = get_object_or_404(Movie, pk=movie_id)
        #p = get_object_or_404(Vote, movie=movie_id)
        m.votes += 1
        m.save()
    except (KeyError):
        # Redisplay the movie voting form.
        return render(request, 'asteroid/detail.html', {
            'movie': m,
            'error_message': "Error:Please vote again.",
        })

        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
    return HttpResponseRedirect(reverse('asteroid:detail', args=(m.id,)))

def welcome(request):
    latest_movies = Movie.objects.filter(category='latest')[:3]
    top_movies = Movie.objects.order_by('-votes')[:3]
    context = {'latest_movies': latest_movies, 'top_movies': top_movies}
    return render(request, 'asteroid/welcome.html', context)

def screen1(request):
    return render(request, 'asteroid/screen1.html')

def search(request):
    if 'q' in request.POST and request.POST['q']:
        q = request.POST['q']
        found_movies = Movie.objects.filter(title__icontains=q)
        if found_movies:
            context = {'movies': found_movies}
            return render(request, 'asteroid/search.html', context)
        else:
            my_key = '662g9gvhs6kcgwyj5aqn5j25'
            tmdb_key = 'fc86d622a7b420430bdc23693434dded'
            found = RT(my_key).search(q, page_limit=4)
            for movie in found:
                try:
                    rt_id = movie['id']
                    o_imdbid = movie['alternate_ids']['imdb']
                    imdbid = ''.join(("tt",o_imdbid))
                    link = "http://api.themoviedb.org/3/movie/"
                    url = "%s%s?api_key=%s"
                    url = url % (link, imdbid, tmdb_key)
                    res = urlopen(url).read()
                    js = json.loads(res)
                    tmdbid = js['id']
                    genre_list = []
                    for g in js['genres']:
                        genre_list.append(g['name'])
                    found_genre = ', '.join(genre_list)
                    print movie['title']
                    image = js['poster_path']
                    simage = ''.join(('http://image.tmdb.org/t/p/w185', image))
                    limage = ''.join(('http://image.tmdb.org/t/p/w342', image))
                    if movie['synopsis']:
                        syno = movie['synopsis']
                    else:
                        syno = js['overview']
                    m = Movie(id = rt_id, imdb_id = o_imdbid, tmdb_id = tmdbid, title = movie['title'], movie_synopsis = syno, critics_score = movie['ratings']['critics_score'], votes = 10, img = image, s_img = simage, l_img = limage, genre = found_genre)
                    m.save()
                    m.update()
                except:
                    print "could not save: "+movie['title']
                    break;
            found_movies = Movie.objects.filter(title__icontains=q)
            context = {'movies': found_movies}
            return render(request, 'asteroid/search.html', context)
    else:
        found_movies = 0
        context = {'movies': found_movies}
        return render(request, 'asteroid/search.html', context)

def about(request):
    context = {'tags': False, 'success': True, 'valid': True}
    return render(request, 'asteroid/about.html', context)

def feedback(request):
    if 'name' in request.POST and request.POST['name']:
        if 'email' in request.POST and request.POST['email']:
            if 'message' in request.POST and request.POST['message']:
                name = request.POST['name']
                email = request.POST['email']
                message = request.POST['message']
                try:
                    validate_email(email)
                except ValidationError as e:
                    valid = False
                else:
                    valid = True
                f = Feedback(fname = str(name), fmail = email, msg = str(message))
                f.save()
                context = {'tags': True, 'success': True, 'valid': valid}

            else:
                context = {'tags': True, 'success': False, 'valid': True}
        else:
            context = {'tags': True, 'success': False, 'valid': True}
    else:
        context = {'tags': True, 'success': False, 'valid': True}
    return render(request, 'asteroid/about.html', context)

asteroid/templates/asteroid/about.html
{% load staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>movieWHEREabouts-About</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'asteroid/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'asteroid/css/jumbotron.css' %}" rel="stylesheet">
    <link href="{% static 'asteroid/css/container.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div>
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'asteroid:screen1' %}">movieWHEREabouts</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'asteroid:welcome' %}">Home</a></li>
                <li class="active"><a href="{% url 'asteroid:about' %}">About</a></li>
                <li><a href="{% url 'asteroid:browse' %}">Browse Movies</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'asteroid:browse_genre' g='action' %}">Action </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='crime' %}">Crime </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='drama' %}">Drama </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='thriller' %}">Thriller </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='documentary' %}">Documentary </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='comedy' %}">Comedy </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='family' %}">Family </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='adventure' %}">Adventure </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='fantasy' %}">Fantasy </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='music' %}">Music </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='sciencefiction' %}">Science Fiction </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='romance' %}">Romance </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='horror' %}">Horror </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='animation' %}">Animation </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='mystery' %}">Mystery </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='war' %}">War </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='history' %}">History </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='western' %}">Western </a></li>
                  </ul>
                </li>
              </ul>
              <form class="navbar-form navbar-right" action="/asteroid/search/" method="post">
                {% csrf_token %}
                <div class="input-group">
                  <input type="text" class="form-control input-sm" placeholder="Quick Search" name="q">
                  <span class="input-group-btn">
                    <button class="btn btn-sm btn-success" type="submit">
                      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </div>
        </nav>

      </div>
    </div>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>About us </h1>
        <p>movieWHEREabouts is an easy to use and duely updated application to enhance user experience when searching for their favourite movies, with all the required information in addition to the best renting or selling options available.</br>Thanks for visiting us!</p>
      </div>
    </div>

    <div class="container">
      <!-- FEEDBACK -->
    {% if tags %}
      {% if success %}
        <div class="alert alert-success" role="alert"><strong>Thanks!</strong>You successfully posted your feedback.</div>
      {% else %}
        {% if valid %}
          <div class="alert alert-danger" role="alert"><strong>Oh snap!</strong>Invalid submission, please try again.</div>
        {% else %}
          <div class="alert alert-danger" role="alert"><strong>Oh snap!</strong>Invalid email, please try submitting again.</div>
        {% endif %}
      {% endif %}
    {% endif %}

    <div class="form-group">
      <h2>Leave us a feedback ?</h2>
      <form action="/asteroid/feedback/" method="post">
        {% csrf_token %}
        <h3>Introduce yourself :</h3></br>
        <input type="text" class="form-control" placeholder="Name" name="name"></br>
        <input type="text" class="form-control" placeholder="Email" name="email"></br>
        <h3>Your message :</h3></br>
        <textarea class="form-control" rows="5" name="message"></textarea></br>
        <button class="btn btn-success" type="submit">Submit</button>
      </form>
    </div>

      <hr>

      <footer>
        <p>&copy; All rights to this website are reserved under the name of <a href="http://facebook.com/shobhit.srivastava91">Shobhit Srivastava</a>. Supported by <a href="http://djangoproject.com/">Django</a>. Powered by <a href="http://rottentomatoes.com/">RottenTomatoes</a> and <a href="http://themoviedb.org/">TMDb</a>. </p>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'asteroid/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

asteroid/templates/asteroid/detail.html
{% load staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>browse-movies</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'asteroid/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'asteroid/css/jumbotron.css' %}" rel="stylesheet">
    <link href="{% static 'asteroid/css/container.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
<!-- NAVBAR
================================================== -->
  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div>
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'asteroid:screen1' %}">movieWHEREabouts</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'asteroid:welcome' %}">Home</a></li>
                <li><a href="{% url 'asteroid:about' %}">About</a></li>
                <li><a href="{% url 'asteroid:browse' %}">Browse Movies</a></li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Genres <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'asteroid:browse_genre' g='action' %}">Action </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='crime' %}">Crime </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='drama' %}">Drama </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='thriller' %}">Thriller </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='documentary' %}">Documentary </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='comedy' %}">Comedy </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='family' %}">Family </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='adventure' %}">Adventure </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='fantasy' %}">Fantasy </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='music' %}">Music </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='sciencefiction' %}">Science Fiction </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='romance' %}">Romance </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='horror' %}">Horror </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='animation' %}">Animation </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='mystery' %}">Mystery </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='war' %}">War </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='history' %}">History </a></li>
                    <li><a href="{% url 'asteroid:browse_genre' g='western' %}">Western </a></li>
                  </ul>
                </li>
              </ul>
              <form class="navbar-form navbar-right" action="/asteroid/search/" method="post">
                {% csrf_token %}
                <div class="input-group">
                  <input type="text" class="form-control input-sm" placeholder="Quick Search" name="q">
                  <span class="input-group-btn">
                    <button class="btn btn-sm btn-success" type="submit">
                      <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    </button>
                  </span>
                </div>
              </form>
            </div>
          </div>
        </nav>

      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->

      {% if movie %}
        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">{{ movie.title }}</h2>
            <p class="lead">
              <img src="{% static 'asteroid/images/rt_score.png' %}" />  {{ movie.critics_score }}%
              <p>{{ movie.movie_synopsis }}</p></br>
              <form action="{% url 'asteroid:voting' movie.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-info" type="submit" >
                  Vote <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
                </button>
              </form>
            </p>
          </div>
          <div class="col-md-5">
            <object class="featurette-image img-responsive" data="{{ movie.l_img }}">
              <img src="{% static 'asteroid/images/l_unavailable.jpg' %}" />
            </object>
          </div>
        </div>

      {% else %}
        <p>Sorry, no movies matched your search criteria.</p>
      {% endif %}
      <hr>

      <footer>
        <p>&copy; All rights to this website are reserved under the name of <a href="http://facebook.com/shobhit.srivastava91">Shobhit Srivastava</a>. Powered by <a href="http://djangoproject.com/">Django</a>.</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'asteroid/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

asteroid/templates/asteroid/index.html
{% load staticfiles %}
{% if latest_movies %}
  <ul>
  {% for movie in latest_movies %}
    <li><a href="{% url 'asteroid:detail' movie.id %}">{{ movie.title }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No results are available.</p>
{% endif %}

asteroid/templates/asteroid/indextop.html
{% load staticfiles %}
{% if top_movies %}
  <ul>
  {% for movie in top_movies %}
    <li><a href="{% url 'asteroid:detail' movie.id %}">{{ movie.title }}</a></li>
  {% endfor %}
  </ul>
{% else %}
  <p>No results are available.</p>
{% endif %}

asteroid/templates/asteroid/paginator.html
<div class="pager">
   {% if has_previous %}
      <span class="page">
      <a href="?page={{ previous }}">&lt; Prev</a>
      </span>
   {% endif %}

   {% if show_first %}
      <span class="page"><a href="?page=1">1</a></span>
      <span class="ellipsis">...</span>
   {% endif %}
   {% for linkpage in page_numbers %}
      {% ifequal linkpage page %}
         <span class="current">{{ page }}</span>
      {% else %}
         <span class="page"><a href="?page={{ linkpage }}"
               >{{ linkpage }}</a></span>
      {% endifequal %}
   {% endfor %}
   {% if show_last %}
      <span class="ellipsis">...</span>
      <span class="page"><a href="?page=last">{{ pages }}</a></span>
   {% endif %}
   {% if has_next %}
      <span class="page"><a href="?page={{ next }}">Next &gt;</a></span>
   {% endif %}
</div>

asteroid/templates/asteroid/screen1.html
{% load staticfiles %}
{% load url from future %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Welcome!</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'asteroid/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'asteroid/css/cover.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">Lights, Camera, Popcorns!</h3>
            </div>
          </div>

          <div class="inner cover">
            <h1 class="cover-heading">movieWHEREabouts</h1>
            <p class="lead">The best place to look out for your favourites in the world of motion pictures!</p>
            <p class="lead">
              <a href="{% url 'asteroid:welcome' %}" class="btn btn-lg btn-default">Take me there &raquo;</a>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>&copy; All rights to this website are reserved under the name of <a href="http://facebook.com/shobhit.srivastava91">Shobhit Srivastava</a>. Supported by <a href="http://djangoproject.com/">Django</a>. Powered by <a href="http://rottentomatoes.com/">RottenTomatoes</a> and <a href="http://themoviedb.org/">TMDb</a>. </p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="{% static 'asteroid/js/bootstrap.min.js' %}"></script>
    <script src="../../assets/js/docs.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>